### ISSUE TITLE
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by wudabingm** [CompVis/depth-fm#16]
Traceback (most recent call last):
  File "/home/lhs/project/nerf...wu/depth-fm-main/inference.py", line 113, in <module>
    main(args)
  File "/home/lhs/project/nerf...wu/depth-fm-main/inference.py", line 64, in main
    model = DepthFM(args.ckpt)
            ^^^^^^^^^^^^^^^^^^
  File "/home/lhs/project/nerf...wu/depth-fm-main/depthfm/dfm.py", line 21, in __init__
    self.vae = AutoencoderKL.from_pretrained(vae_id, subfolder="vae")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhs/.conda/envs/depthfm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lhs/.conda/envs/depthfm/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 569, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "/home/lhs/.conda/envs/depthfm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lhs/.conda/envs/depthfm/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 402, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**Comment by GaoLL1026** [comment]
我也遇到了这个问题  请问解决了吗

**Comment by Xudong-Mao** [comment]
The problem may have been resolved by utilizing Google colab, but I encountered the same issue when attempting to run it locally.

**Comment by wudabingm** [comment]
> The problem may have been resolved by utilizing Google colab, but I encountered the same issue when attempting to run it locally.

Could you please tell me how to operate google colab? In addition, if the config error is reported, I can run it locally, but not on the server

**Comment by wudabingm** [comment]
> 我也遇到了这个问题 请问解决了吗

还没有解决，好兄弟

**Comment by Xudong-Mao** [comment]
> > The problem may have been resolved by utilizing Google colab, but I encountered the same issue when attempting to run it locally.
> 
> Could you please tell me how to operate google colab? In addition, if the config error is reported, I can run it locally, but not on the server
Just look at the code in the **inference.ipynb** file and change the
 Inference` dev = 'cuda:4 ' ` to `dev = 'cuda:0'` and execute all the code from start to finish.

**Comment by wudabingm** [comment]
> > > The problem may have been resolved by utilizing Google colab, but I encountered the same issue when attempting to run it locally.
> > 
> > 
> > Could you please tell me how to operate google colab? In addition, if the config error is reported, I can run it locally, but not on the server
> > Just look at the code in the **inference.ipynb** file and change the
> > Inference`dev = 'cuda:4 '` to `dev = 'cuda:0'` and execute all the code from start to finish.

But I started reporting errors in the inference.ipynb load model step of the code, the same error, runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**Comment by gopin95** [comment]
有人解决了吗？

**Comment by woshiwahah** [comment]
> 有人解决了吗？

HF_ENDPOINT=https://hf-mirror.com python inference.py    --num_steps 2  --ensemble_size 4    --img assets/dog.png    --ckpt checkpoints/depthfm-v1.ckpt
这个有效

**Comment by yhy-2000** [comment]
fix it by change
`pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "./pretrained_model/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16
)`
 to 
`pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "./pretrained_model/stable-diffusion-v1-5", controlnet=controlnet, safety_checker=None, torch_dtype=torch.float16
)`

**Comment by Hxy-Gra** [comment]
我自己的原因是在 from_pretrained 参数里没有正确指定 safety_checker=None 这个变量，加进去就好了

**Comment by linear-al342** [comment]
我的解决方案是，把depthfm里面dfm.py文件中DepthFM类里初始化里面的vae_id改成stable-diffusion-2-depth自己的本地地址，国内在https://hf-mirror.com/stabilityai/stable-diffusion-2-depth/tree/main这里下载

**Comment by fishedCat** [comment]
我是因为网络原因，连接不上，开了梯子就好了
